// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8LcZ-W7JnRka_cO-S8rpadR0qFRzzNUQ',
    appId: '1:673968607580:web:c7965530f669dccf947199',
    messagingSenderId: '673968607580',
    projectId: 'aidio-reserve',
    authDomain: 'aidio-reserve.firebaseapp.com',
    storageBucket: 'aidio-reserve.appspot.com',
    measurementId: 'G-BV1DKLQBMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiF5b7Jwn0FGK0t0MpybiVjLFfNK07kk',
    appId: '1:673968607580:android:409efc5593fac362947199',
    messagingSenderId: '673968607580',
    projectId: 'aidio-reserve',
    storageBucket: 'aidio-reserve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDe80gYYDajl9bGI82RgI_O2Mw6Oanx0',
    appId: '1:673968607580:ios:3e745fce0dead757947199',
    messagingSenderId: '673968607580',
    projectId: 'aidio-reserve',
    storageBucket: 'aidio-reserve.appspot.com',
    iosBundleId: 'app.web.aiTrip2',
  );

}